#theme: jekyll-theme-minimal
#theme : Huxpro 
#title: 🔭🌌🚀💻
#description: Houda Haidar's CV

# Site settings
title: Houda Haidar
description: Astrophysics PhD student
# baseurl: "" # the subpath of your site, e.g. /blog
url: "https://blackhole-girl.github.io" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Houda Haudar
user_description:  to do
user_title: Astrophysics PhD student
email: to do
# twitter_username: blackholephd
#linkedin_username: 
#github_username:  murraco
# medium_username: lorem_ipsum
# medium_url: lorem_ipsum.medium.com
# gplus_username:  lorem_ipsum

#exclude: ['package.json', 'src', 'node_modules', 'vendor']
